### ISSUE TITLE
Clean up language in readme

### ISSUE THREAD

**Issue by dougwein** [planetmercury/mercury-challenge#25]
Posted by catskills in forum:

There is language in the Installation section about getting Visual Studio or CMake. This only necessary to build the unreleased official scoring package, and this language could be removed to eliminate confusion.

**Comment by gibbonsjohnm** [comment]
Visual Studio and CMake are required for Windows and Linux, respectively. Each OS has its own section in the readme, with specific installation instructions. If the user is not on that OS, those instructions can be ignored.
