### ISSUE TITLE
IPython notebook examples for submission

### ISSUE THREAD

**Issue by dougwein** [planetmercury/mercury-challenge#26]
Posted by catskills in the forum:

Also I strongly recommend creating an IPython notebook which completely demonstrates, in Python, submitting a forecast using the JSON API, and, assuming the capability can be provided, querying the system to bring back a summary or the contents of all of the forecasts that have been submitted.

**Comment by peterhaglich** [comment]
See #28.  New notebook is 
https://github.com/planetmercury/mercury-challenge/blob/master/doc/Warning%20Submission%20Using%20Python.ipynb
