### ISSUE TITLE
History of Warnings

### ISSUE THREAD

**Issue by rebecca-allegar** [planetmercury/mercury-challenge#27]
Would like a feature that lists all submitted open warnings, so that we can keep track of the current state what was received

**Comment by planetmercury** [comment]
This is now completely implemented and documented.  See https://github.com/planetmercury/mercury-challenge/wiki/Retrieving-Warning-History and https://github.com/planetmercury/mercury-challenge/blob/master/doc/Retrieving%20Warning%20History%20Using%20Python.ipynb to learn how to use this feature.
