### ISSUE TITLE
"Participant Not Matched" error

### ISSUE THREAD

**Issue by thMike** [planetmercury/mercury-challenge#49]
Username: eman98
Team: 0xDEADBEEF

I generated the token before I created the team. Whenever we try to post to the endpoint we get the "Participant Not Matched" error.

**Comment by dougwein** [comment]
@thMike you must submit as the user who generated the token. Example: My handle is testhandle, my token is 1234. My "participant_id" must be "testhandle" and my x-api-key must be "testhandle:1234"

I cannot submit with participant_id as "otherhandle" and x-api-key as "testhandle:1234"

**Comment by thMike** [comment]
@dougwein I thought it was implied but I'll reformulate.

I am the team captain but I generated the token before I created the team. When we are trying to post to the endpoint with my topcoder nickname and my token, we receive a "Participant Not Matched" error.

**Comment by dougwein** [comment]
@thMike regardless of the team name, team captains must still submit using their handle as participant_id. I will send you an e-mail to continue this thread and troubleshooting outside of public forum, also have some teaming agreements that need to be filled out.

**Comment by peterhaglich** [comment]
Please see <https://github.com/planetmercury/mercury-challenge/blob/master/doc/Warning%20Submission%20Using%20Python.ipynb> for some more information that may help you.
