### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by thMike** [planetmercury/mercury-challenge#50]
We're getting `{
  "result": "error",
  "Invalid warnings": 1,
  "Total operations": 1,
  "Existing warnings updated": 0,
  "reason": "Payload item 1: Unknown event type \"Civil Unrest Daily\"",
  "New warnings or versions inserted": 0
}`

While sending `{
  'participant_id': 'eman98',
  'payload': [
    {
      'Warning_ID': '1539437499.5568871EGYPT',
      'Event_Type': 'Civil Unrest Daily',
      'Event_Date': '2018-10-16',
      'Country': 'Egypt',
      'Count': 1
    }
  ]
}`

As far as I can see from the handbook, 'Civil Unrest Daily' is a legal name.

**Comment by peterhaglich** [comment]
The proper event type is `Civil Unrest` without a modifier.  Pages 18-20 of the current handbook document this.  <https://github.com/planetmercury/mercury-challenge/blob/master/doc/handbook/Mercury%20Challenge%20-%20Handbook.pdf>.  You can also look at the Baserate warning files for more guidance.  <https://github.com/planetmercury/mercury-challenge/blob/master/data/baserate_warnings/baserate_cu_warnings/Egypt/BR_Warnings_Egypt_2018-09-23_to_2018-10-04.json> for example.
